
build:
	docker build -t vehicle-type-classificator .

run:
	docker run -d --name vehicle-type-classificator-app -p 8000:8000 --rm vehicle-type-classificator

down:
	docker stop vehicle-type-classificator-app
